spring:
  profiles:
    active: druid

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

server:
  port: 8081

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml, classpath*:/mapper/*/*Mapper.xml
  type-aliases-package: com.fumei.bg.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:logback.xml


profile:
  path: E:/profiles/static
#  path: /home/static


Token:
  expireTime: 1800000
  secret: zkfm
  header: Authorization

Banner:
  maxBannerCount: 5